### ISSUE TITLE
Switch host for mathjax?

### ISSUE THREAD

**Issue by draben** [topepo/FES#49]
Would it be possible to switch the CDN for mathjax? I work in a US corporation that unfortunately blocks access to bootcss due to the country that hosts the site. Thus, all of the mathematical notation throughout the book does not render. Raw LaTeX is displayed instead.

A number of books published to bookdown.org suffer from the same issue.

We publish internally using a number of rendering packages, including bookdown. For example, one switch (and minor upgrade) that we employ is to go from:

```md
https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
```
to
```md
https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
```
by way of
```yaml
output: 
  bookdown::html_document2:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_HTMLorMML.js"
```

Thanks!
